/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.BRM.CATV.Payment;

public class CATVPaymentMaster {
	@com.google.gson.annotations.SerializedName("MSO_OP_PYMT_COLLECT_outputFlist")
	private MSO_OP_PYMT_COLLECT_outputFlist mso_op_pymt_collect_outputflist;

 	public void setMso_op_pymt_collect_outputflist(MSO_OP_PYMT_COLLECT_outputFlist mso_op_pymt_collect_outputflist) {
		this.mso_op_pymt_collect_outputflist = mso_op_pymt_collect_outputflist;
	}

	public MSO_OP_PYMT_COLLECT_outputFlist getMso_op_pymt_collect_outputflist() {
		return mso_op_pymt_collect_outputflist;
	}

}