/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.BRM.CATV.Payment;

public class MSO_OP_PYMT_COLLECT_outputFlist {
	@com.google.gson.annotations.SerializedName("USERID")
	private java.lang.String userid;

 	public void setUserid(java.lang.String userid) {
		this.userid = userid;
	}

	public java.lang.String getUserid() {
		return userid;
	}

	@com.google.gson.annotations.SerializedName("BRANCH_NO")
	private java.lang.String branch_no;

 	public void setBranch_no(java.lang.String branch_no) {
		this.branch_no = branch_no;
	}

	public java.lang.String getBranch_no() {
		return branch_no;
	}

	@com.google.gson.annotations.SerializedName("CREATED_T")
	private java.lang.String created_t;

 	public void setCreated_t(java.lang.String created_t) {
		this.created_t = created_t;
	}

	public java.lang.String getCreated_t() {
		return created_t;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_PYMT_CHANNEL")
	private java.lang.String mso_fld_pymt_channel;

 	/*public void setMso_fld_pymt_channel(java.lang.Integer mso_fld_pymt_channel) {
		this.mso_fld_pymt_channel = mso_fld_pymt_channel;
	}*/

	public java.lang.Integer getMso_fld_pymt_channel() {
		if(mso_fld_pymt_channel == null || mso_fld_pymt_channel.equals(""))
			return 0;
		return Integer.valueOf(mso_fld_pymt_channel);
	}

	@com.google.gson.annotations.SerializedName("RECEIPT_NO")
	private java.lang.String receipt_no;

 	public void setReceipt_no(java.lang.String receipt_no) {
		this.receipt_no = receipt_no;
	}

	public java.lang.String getReceipt_no() {
		return receipt_no;
	}

	@com.google.gson.annotations.SerializedName("BANK_CODE")
	private java.lang.String bank_code;

 	public void setBank_code(java.lang.String bank_code) {
		this.bank_code = bank_code;
	}

	public java.lang.String getBank_code() {
		return bank_code;
	}

	@com.google.gson.annotations.SerializedName("PAY_TYPE")
	private java.lang.Integer pay_type;

 	public void setPay_type(java.lang.Integer pay_type) {
		this.pay_type = pay_type;
	}

	public java.lang.Integer getPay_type() {
		return pay_type;
	}

	@com.google.gson.annotations.SerializedName("TYPE")
	private java.lang.String type;

 	/*public void setType(java.lang.Integer type) {
		this.type = type;
	}*/

	public java.lang.Integer getType() {
		if(type == null || type.equals(""))
			return 0;
		return Integer.valueOf(type);
	}

	@com.google.gson.annotations.SerializedName("FLAGS")
	private java.lang.String flags;

 	/*public void setFlags(java.lang.Integer flags) {
		this.flags = flags;
	}*/

	public java.lang.Integer getFlags() {
		if(flags == null || flags.equals(""))
			return 0;
		return Integer.valueOf(flags);
	}

	@com.google.gson.annotations.SerializedName("STATUS_FLAGS")
	private java.lang.String status_flags;

 	/*public void setStatus_flags(java.lang.Integer status_flags) {
		this.status_flags = status_flags;
	}*/

	public java.lang.Integer getStatus_flags() {
		if(status_flags == null || status_flags.equals(""))
			return 0;
		return Integer.valueOf(status_flags);
	}

	@com.google.gson.annotations.SerializedName("AMOUNT")
	private java.lang.String amount;

 	/*public void setAmount(java.lang.Integer amount) {
		this.amount = amount;
	}*/

	public java.lang.Double getAmount() {
		if(amount == null || amount.equals(""))
			return 0d;
		return Double.valueOf(status_flags);
	}

	@com.google.gson.annotations.SerializedName("PROGRAM_NAME")
	private java.lang.String program_name;

 	public void setProgram_name(java.lang.String program_name) {
		this.program_name = program_name;
	}

	public java.lang.String getProgram_name() {
		return program_name;
	}

	@com.google.gson.annotations.SerializedName("REFERENCE_ID")
	private java.lang.String reference_id;

 	public void setReference_id(java.lang.String reference_id) {
		this.reference_id = reference_id;
	}

	public java.lang.String getReference_id() {
		return reference_id;
	}

	@com.google.gson.annotations.SerializedName("STATUS")
	private java.lang.String status;

 	/*public void setStatus(java.lang.Integer status) {
		this.status = status;
	}*/

	public java.lang.Integer getStatus() {
		if(status == null || status.equals(""))
			return 0;
		return Integer.valueOf(status);
	}

	@com.google.gson.annotations.SerializedName("IP_ADDRESS")
	private java.lang.String ip_address;

 	public void setIp_address(java.lang.String ip_address) {
		this.ip_address = ip_address;
	}

	public java.lang.String getIp_address() {
		return ip_address;
	}

	@com.google.gson.annotations.SerializedName("CHECK_NO")
	private java.lang.String check_no;

 	public void setCheck_no(java.lang.String check_no) {
		this.check_no = check_no;
	}

	public java.lang.String getCheck_no() {
		return check_no;
	}

	@com.google.gson.annotations.SerializedName("EFFECTIVE_T")
	private java.lang.String effective_t;

 	public void setEffective_t(java.lang.String effective_t) {
		this.effective_t = effective_t;
	}

	public java.lang.String getEffective_t() {
		return effective_t;
	}

	@com.google.gson.annotations.SerializedName("POID")
	private java.lang.String poid;

 	public void setPoid(java.lang.String poid) {
		this.poid = poid;
	}

	public java.lang.String getPoid() {
		return poid;
	}

	@com.google.gson.annotations.SerializedName("BANK_NAME")
	private java.lang.String bank_name;

 	public void setBank_name(java.lang.String bank_name) {
		this.bank_name = bank_name;
	}

	public java.lang.String getBank_name() {
		return bank_name;
	}

	@com.google.gson.annotations.SerializedName("DESCR")
	private java.lang.String descr;

 	public void setDescr(java.lang.String descr) {
		this.descr = descr;
	}

	public java.lang.String getDescr() {
		return descr;
	}

	@com.google.gson.annotations.SerializedName("ADDRESS")
	private java.lang.String address;

 	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getAddress() {
		return address;
	}

	@com.google.gson.annotations.SerializedName("CHANNEL")
	private java.lang.String channel;

 	public void setChannel(java.lang.String channel) {
		this.channel = channel;
	}

	public java.lang.String getChannel() {
		return channel;
	}

	@com.google.gson.annotations.SerializedName("BANK_ACCOUNT_NO")
	private java.lang.String bank_account_no;

 	public void setBank_account_no(java.lang.String bank_account_no) {
		this.bank_account_no = bank_account_no;
	}

	public java.lang.String getBank_account_no() {
		return bank_account_no;
	}

	@com.google.gson.annotations.SerializedName("NAME")
	private java.lang.String name;

 	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

	@com.google.gson.annotations.SerializedName("ACCOUNT_NO")
	private java.lang.String account_no;

 	/*public void setAccount_no(java.lang.Integer account_no) {
		this.account_no = account_no;
	}*/

	public java.lang.Long getAccount_no() {
		if(account_no == null || account_no.equals(""))
			return 0l;
		return Long.valueOf(account_no);
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_SERVICE_TYPE")
	private java.lang.String mso_fld_service_type;

 	/*public void setMso_fld_service_type(java.lang.Integer mso_fld_service_type) {
		this.mso_fld_service_type = mso_fld_service_type;
	}*/

	public java.lang.Integer getMso_fld_service_type() {
		if(mso_fld_service_type == null || mso_fld_service_type.equals(""))
			return 0;
		return Integer.valueOf(mso_fld_service_type);
	}

	@com.google.gson.annotations.SerializedName("ACCOUNT_OBJ")
	private java.lang.String account_obj;

 	public void setAccount_obj(java.lang.String account_obj) {
		this.account_obj = account_obj;
	}

	public java.lang.String getAccount_obj() {
		return account_obj;
	}

	@com.google.gson.annotations.SerializedName("START_T")
	private java.lang.String start_t;

 	public void setStart_t(java.lang.String start_t) {
		this.start_t = start_t;
	}

	public java.lang.String getStart_t() {
		return start_t;
	}

	@com.google.gson.annotations.SerializedName("UNAPPLIED_AMOUNT")
	private java.lang.String unapplied_amount;

 	/*public void setUnapplied_amount(java.lang.Integer unapplied_amount) {
		this.unapplied_amount = unapplied_amount;
	}*/

	public java.lang.Double getUnapplied_amount() {
		if(unapplied_amount == null || unapplied_amount.equals(""))
			return 0d;
		return Double.valueOf(flags);
	}

	@com.google.gson.annotations.SerializedName("END_T")
	private java.lang.String end_t;

 	public void setEnd_t(java.lang.String end_t) {
		this.end_t = end_t;
	}

	public java.lang.String getEnd_t() {
		return end_t;
	}

}