/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.BRM.CATV.GetCustomer;

public class PRODUCTS {
	@com.google.gson.annotations.SerializedName("PACKAGE_ID")
	private java.lang.Integer package_id;

 	public void setPackage_id(java.lang.Integer package_id) {
		this.package_id = package_id;
	}

	public java.lang.Integer getPackage_id() {
		return package_id;
	}

	@com.google.gson.annotations.SerializedName("EFFECTIVE_T")
	private java.lang.String effective_t;

 	public void setEffective_t(java.lang.String effective_t) {
		this.effective_t = effective_t;
	}

	public java.lang.String getEffective_t() {
		return effective_t;
	}

	@com.google.gson.annotations.SerializedName("PRODUCT_OBJ")
	private java.lang.String product_obj;

 	public void setProduct_obj(java.lang.String product_obj) {
		this.product_obj = product_obj;
	}

	public java.lang.String getProduct_obj() {
		return product_obj;
	}

	@com.google.gson.annotations.SerializedName("USAGE_START_T")
	private java.lang.String usage_start_t;

 	public void setUsage_start_t(java.lang.String usage_start_t) {
		this.usage_start_t = usage_start_t;
	}

	public java.lang.String getUsage_start_t() {
		return usage_start_t;
	}

	@com.google.gson.annotations.SerializedName("POID")
	private java.lang.String poid;

 	public void setPoid(java.lang.String poid) {
		this.poid = poid;
	}

	public java.lang.String getPoid() {
		return poid;
	}

	@com.google.gson.annotations.SerializedName("PURCHASE_START_T")
	private java.lang.String purchase_start_t;

 	public void setPurchase_start_t(java.lang.String purchase_start_t) {
		this.purchase_start_t = purchase_start_t;
	}

	public java.lang.String getPurchase_start_t() {
		return purchase_start_t;
	}

	@com.google.gson.annotations.SerializedName("CYCLE_START_T")
	private java.lang.String cycle_start_t;

 	public void setCycle_start_t(java.lang.String cycle_start_t) {
		this.cycle_start_t = cycle_start_t;
	}

	public java.lang.String getCycle_start_t() {
		return cycle_start_t;
	}

	@com.google.gson.annotations.SerializedName("DEAL_OBJ")
	private java.lang.String deal_obj;

 	public void setDeal_obj(java.lang.String deal_obj) {
		this.deal_obj = deal_obj;
	}

	public java.lang.String getDeal_obj() {
		return deal_obj;
	}

	@com.google.gson.annotations.SerializedName("elem")
	private java.lang.String elem;

 	/*public void setElem(java.lang.Integer elem) {
		this.elem = elem;
	}*/

	public java.lang.Integer getElem() {
		if(elem == null || elem.equals(""))
			return 0;
		else
		return Integer.valueOf(elem);
	}

	@com.google.gson.annotations.SerializedName("STATUS")
	private java.lang.Integer status;

 	public void setStatus(java.lang.Integer status) {
		this.status = status;
	}

	public java.lang.Integer getStatus() {
		return status;
	}

	@com.google.gson.annotations.SerializedName("PURCHASE_END_T")
	private java.lang.String purchase_end_t;

 	public void setPurchase_end_t(java.lang.String purchase_end_t) {
		this.purchase_end_t = purchase_end_t;
	}

	public java.lang.String getPurchase_end_t() {
		return purchase_end_t;
	}

}