/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.BRM.CATV.GetCustomer;


public class PLANElement {
	/*@com.google.gson.annotations.SerializedName("PRODUCTS")
	private PRODUCTS products;

 	public void setProducts(PRODUCTS products) {
		this.products = products;
	}

	public PRODUCTS getProducts() {
		return products;
	}*/

	@com.google.gson.annotations.SerializedName("PRODUCTS")
	private PRODUCTElement[] products;

	public void setProducts(PRODUCTElement[] products) {
		this.products = products;
	}

	public PRODUCTElement[] getProducts() {
		return products;
	}
	
	@com.google.gson.annotations.SerializedName("PLAN_OBJ")
	private java.lang.String plan_obj;

 	public void setPlan_obj(java.lang.String plan_obj) {
		this.plan_obj = plan_obj;
	}

	public java.lang.String getPlan_obj() {
		return plan_obj;
	}

	@com.google.gson.annotations.SerializedName("elem")
	private java.lang.String elem;

 	/*public void setElem(java.lang.Integer elem) {
		this.elem = elem;
	}*/

	public java.lang.Integer getElem() {
		if(elem == null || elem.equals(""))
			return 0;
		else
		return Integer.valueOf(elem);
	}

}