/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.BRM.CATV.GetCustomer;

public class SERVICE_INFO {
	@com.google.gson.annotations.SerializedName("SERVICES")
	private SERVICEElement[] services;

 	public void setServices(SERVICEElement[] services) {
		this.services = services;
	}

	public SERVICEElement[] getServices() {
		return services;
	}

}