/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.BRM.CATV.GetCustomer;

public class MSO_FLD_ORG_STRUCTURE {
	@com.google.gson.annotations.SerializedName("ACCOUNT_NO")
	private java.lang.String account_no;

 	public void setAccount_no(java.lang.String account_no) {
		this.account_no = account_no;
	}

	public java.lang.String getAccount_no() {
		return account_no;
	}

	@com.google.gson.annotations.SerializedName("NAMEINFO")
	private NAMEINFO nameinfo;

 	public void setNameinfo(NAMEINFO nameinfo) {
		this.nameinfo = nameinfo;
	}

	public NAMEINFO getNameinfo() {
		return nameinfo;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_PP_TYPE")
	private java.lang.Integer mso_fld_pp_type;

 	public void setMso_fld_pp_type(java.lang.Integer mso_fld_pp_type) {
		this.mso_fld_pp_type = mso_fld_pp_type;
	}

	public java.lang.Integer getMso_fld_pp_type() {
		return mso_fld_pp_type;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_PAN_NO")
	private java.lang.String mso_fld_pan_no;

 	public void setMso_fld_pan_no(java.lang.String mso_fld_pan_no) {
		this.mso_fld_pan_no = mso_fld_pan_no;
	}

	public java.lang.String getMso_fld_pan_no() {
		return mso_fld_pan_no;
	}

	@com.google.gson.annotations.SerializedName("PROFILE_OBJ")
	private java.lang.String profile_obj;

 	public void setProfile_obj(java.lang.String profile_obj) {
		this.profile_obj = profile_obj;
	}

	public java.lang.String getProfile_obj() {
		return profile_obj;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_SALES_CLOSE_TYPE")
	private java.lang.Integer mso_fld_sales_close_type;

 	public void setMso_fld_sales_close_type(java.lang.Integer mso_fld_sales_close_type) {
		this.mso_fld_sales_close_type = mso_fld_sales_close_type;
	}

	public java.lang.Integer getMso_fld_sales_close_type() {
		return mso_fld_sales_close_type;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_LCO_OBJ")
	private java.lang.String mso_fld_lco_obj;

 	public void setMso_fld_lco_obj(java.lang.String mso_fld_lco_obj) {
		this.mso_fld_lco_obj = mso_fld_lco_obj;
	}

	public java.lang.String getMso_fld_lco_obj() {
		return mso_fld_lco_obj;
	}

	@com.google.gson.annotations.SerializedName("CUSTOMER_TYPE")
	private java.lang.Integer customer_type;

 	public void setCustomer_type(java.lang.Integer customer_type) {
		this.customer_type = customer_type;
	}

	public java.lang.Integer getCustomer_type() {
		return customer_type;
	}

	@com.google.gson.annotations.SerializedName("PARENT")
	private java.lang.String parent;

 	public void setParent(java.lang.String parent) {
		this.parent = parent;
	}

	public java.lang.String getParent() {
		return parent;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_WELCOME_CALL_STATUS")
	private java.lang.Integer mso_fld_welcome_call_status;

 	public void setMso_fld_welcome_call_status(java.lang.Integer mso_fld_welcome_call_status) {
		this.mso_fld_welcome_call_status = mso_fld_welcome_call_status;
	}

	public java.lang.Integer getMso_fld_welcome_call_status() {
		return mso_fld_welcome_call_status;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_SDT_OBJ")
	private java.lang.String mso_fld_sdt_obj;

 	public void setMso_fld_sdt_obj(java.lang.String mso_fld_sdt_obj) {
		this.mso_fld_sdt_obj = mso_fld_sdt_obj;
	}

	public java.lang.String getMso_fld_sdt_obj() {
		return mso_fld_sdt_obj;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_CATV_ACCOUNT_OBJ")
	private java.lang.String mso_fld_catv_account_obj;

 	public void setMso_fld_catv_account_obj(java.lang.String mso_fld_catv_account_obj) {
		this.mso_fld_catv_account_obj = mso_fld_catv_account_obj;
	}

	public java.lang.String getMso_fld_catv_account_obj() {
		return mso_fld_catv_account_obj;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_SALESMAN_OBJ")
	private java.lang.String mso_fld_salesman_obj;

 	public void setMso_fld_salesman_obj(java.lang.String mso_fld_salesman_obj) {
		this.mso_fld_salesman_obj = mso_fld_salesman_obj;
	}

	public java.lang.String getMso_fld_salesman_obj() {
		return mso_fld_salesman_obj;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_JV_OBJ")
	private java.lang.String mso_fld_jv_obj;

 	public void setMso_fld_jv_obj(java.lang.String mso_fld_jv_obj) {
		this.mso_fld_jv_obj = mso_fld_jv_obj;
	}

	public java.lang.String getMso_fld_jv_obj() {
		return mso_fld_jv_obj;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_DT_OBJ")
	private java.lang.String mso_fld_dt_obj;

 	public void setMso_fld_dt_obj(java.lang.String mso_fld_dt_obj) {
		this.mso_fld_dt_obj = mso_fld_dt_obj;
	}

	public java.lang.String getMso_fld_dt_obj() {
		return mso_fld_dt_obj;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_DAS_TYPE")
	private java.lang.String mso_fld_das_type;

 	public void setMso_fld_das_type(java.lang.String mso_fld_das_type) {
		this.mso_fld_das_type = mso_fld_das_type;
	}

	public java.lang.String getMso_fld_das_type() {
		return mso_fld_das_type;
	}

}