/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.BRM.CATV.GetCustomer;

public class BILLINFO {
	@com.google.gson.annotations.SerializedName("ACTUAL_LAST_BILL_T")
	private java.lang.String actual_last_bill_t;

 	public void setActual_last_bill_t(java.lang.String actual_last_bill_t) {
		this.actual_last_bill_t = actual_last_bill_t;
	}

	public java.lang.String getActual_last_bill_t() {
		return actual_last_bill_t;
	}

	@com.google.gson.annotations.SerializedName("BAL_GRP_OBJ")
	private java.lang.String bal_grp_obj;

 	public void setBal_grp_obj(java.lang.String bal_grp_obj) {
		this.bal_grp_obj = bal_grp_obj;
	}

	public java.lang.String getBal_grp_obj() {
		return bal_grp_obj;
	}

	@com.google.gson.annotations.SerializedName("ACTG_CYCLE_DOM")
	private java.lang.String actg_cycle_dom;

 	public void setActg_cycle_dom(java.lang.String actg_cycle_dom) {
		this.actg_cycle_dom = actg_cycle_dom;
	}

	public java.lang.String getActg_cycle_dom() {
		return actg_cycle_dom;
	}

	@com.google.gson.annotations.SerializedName("PENDINGBILL_DUE")
	private java.lang.String pendingbill_due;

 	/*public void setPendingbill_due(java.lang.String pendingbill_due) {
		this.pendingbill_due = pendingbill_due;
	}*/

	public java.lang.Double getPendingbill_due() {
		if(pendingbill_due == null || pendingbill_due.equalsIgnoreCase(""))
			return 0.0d;
		else
			return Double.valueOf(pendingbill_due);
	}

	@com.google.gson.annotations.SerializedName("OPENBILL_DUE")
	private java.lang.String openbill_due;

 	/*public void setOpenbill_due(java.lang.String openbill_due) {
		this.openbill_due = openbill_due;
	}*/

	public java.lang.Double getOpenbill_due() {
		if(openbill_due == null || openbill_due.equalsIgnoreCase(""))
			return 0.0d;
		else
			return Double.valueOf(openbill_due);
	}

	@com.google.gson.annotations.SerializedName("AMOUNT_ORIGINAL_PAYMENT")
	private java.lang.String amount_original_payment;

 	/*public void setAmount_original_payment(java.lang.String amount_original_payment) {
		this.amount_original_payment = amount_original_payment;
	}*/

	public java.lang.Double getAmount_original_payment() {
		if(amount_original_payment == null || amount_original_payment.equalsIgnoreCase(""))
			return 0.0d;
		else
			return Double.valueOf(amount_original_payment);
	}

	@com.google.gson.annotations.SerializedName("DISPUTED")
	private java.lang.String disputed;

 	/*public void setDisputed(java.lang.String disputed) {
		this.disputed = disputed;
	}*/

	public java.lang.Double getDisputed() {
		if(disputed == null || disputed.equalsIgnoreCase(""))
			return 0.0d;
		else
			return Double.valueOf(disputed);
	}

	@com.google.gson.annotations.SerializedName("INDICATOR")
	private java.lang.String indicator;

 	/*public void setIndicator(java.lang.String indicator) {
		this.indicator = indicator;
	}*/

	public java.lang.Integer getIndicator() {
		if(indicator == null || indicator.equalsIgnoreCase(""))
			return 0;
		else
			return Integer.valueOf(indicator);
	}

	@com.google.gson.annotations.SerializedName("AR_BILLINFO_OBJ")
	private java.lang.String ar_billinfo_obj;

 	public void setAr_billinfo_obj(java.lang.String ar_billinfo_obj) {
		this.ar_billinfo_obj = ar_billinfo_obj;
	}

	public java.lang.String getAr_billinfo_obj() {
		return ar_billinfo_obj;
	}

	@com.google.gson.annotations.SerializedName("ACTG_FUTURE_T")
	private java.lang.String actg_future_t;

 	public void setActg_future_t(java.lang.String actg_future_t) {
		this.actg_future_t = actg_future_t;
	}

	public java.lang.String getActg_future_t() {
		return actg_future_t;
	}

	@com.google.gson.annotations.SerializedName("AMOUNT_ADJUSTED")
	private java.lang.String amount_adjusted;

 	/*public void setAmount_adjusted(java.lang.String amount_adjusted) {
		this.amount_adjusted = amount_adjusted;
	}*/

	public java.lang.Double getAmount_adjusted() {
		if(amount_adjusted == null || amount_adjusted.equals(""))
			return 0.0d;
		else
		return Double.valueOf(amount_adjusted);
	}

	@com.google.gson.annotations.SerializedName("PAY_TYPE")
	private java.lang.String pay_type;

 	public void setPay_type(java.lang.String pay_type) {
		this.pay_type = pay_type;
	}

	public java.lang.String getPay_type() {
		return pay_type;
	}

	@com.google.gson.annotations.SerializedName("elem")
	private java.lang.String elem;

 	/*public void setElem(java.lang.Integer elem) {
		this.elem = elem;
	}*/
	public java.lang.Integer getElem() {
		if(elem == null || elem.equals(""))
			return 0;
		return Integer.valueOf(elem);
	}

	@com.google.gson.annotations.SerializedName("CURRENT_BAL")
	private java.lang.String current_bal;

 	/*public void setCurrent_bal(java.lang.String current_bal) {
		this.current_bal = current_bal;
	}*/

	public java.lang.Double getCurrent_bal() {
		if(current_bal == null || current_bal.equalsIgnoreCase(""))
			return 0.0d;
		return Double.valueOf(current_bal);
	}

	@com.google.gson.annotations.SerializedName("TOTAL_DUE")
	private java.lang.String total_due;

 	/*public void setTotal_due(java.lang.String total_due) {
		this.total_due = total_due;
	}*/

	public java.lang.Double getTotal_due() {
		if(total_due == null || total_due.equalsIgnoreCase(""))
			return 0.0d;
		return Double.valueOf(total_due);
	}
	
	@com.google.gson.annotations.SerializedName("MSO_FLD_TDS_RECV")
	private java.lang.String mso_fld_tds_recv;

 	public void setMso_fld_tds_recv(java.lang.String mso_fld_tds_recv) {
		this.mso_fld_tds_recv = mso_fld_tds_recv;
	}

	public java.lang.String getMso_fld_tds_recv() {
		return mso_fld_tds_recv;
	}

	@com.google.gson.annotations.SerializedName("POID")
	private java.lang.String poid;

 	public void setPoid(java.lang.String poid) {
		this.poid = poid;
	}

	public java.lang.String getPoid() {
		return poid;
	}

	@com.google.gson.annotations.SerializedName("DELIVERY_PREFER")
	private java.lang.String delivery_prefer;

 	public void setDelivery_prefer(java.lang.String delivery_prefer) {
		this.delivery_prefer = delivery_prefer;
	}

	public java.lang.String getDelivery_prefer() {
		return delivery_prefer;
	}

	@com.google.gson.annotations.SerializedName("NEXT_BILL_T")
	private java.lang.String next_bill_t;

 	public void setNext_bill_t(java.lang.String next_bill_t) {
		this.next_bill_t = next_bill_t;
	}

	public java.lang.String getNext_bill_t() {
		return next_bill_t;
	}

	@com.google.gson.annotations.SerializedName("CREDIT_LIMIT")
	private java.lang.String credit_limit;

 	/*public void setCredit_limit(java.lang.String credit_limit) {
		this.credit_limit = credit_limit;
	}*/

	public java.lang.Double getCredit_limit() {
		if(credit_limit == null || credit_limit.equalsIgnoreCase(""))
			return 0.0d;
		else
		return Double.valueOf(credit_limit);
	}

	@com.google.gson.annotations.SerializedName("PAYINFO_OBJ")
	private java.lang.String payinfo_obj;

 	public void setPayinfo_obj(java.lang.String payinfo_obj) {
		this.payinfo_obj = payinfo_obj;
	}

	public java.lang.String getPayinfo_obj() {
		return payinfo_obj;
	}

	@com.google.gson.annotations.SerializedName("LAST_BILL_T")
	private java.lang.String last_bill_t;

 	public void setLast_bill_t(java.lang.String last_bill_t) {
		this.last_bill_t = last_bill_t;
	}

	public java.lang.String getLast_bill_t() {
		return last_bill_t;
	}

	@com.google.gson.annotations.SerializedName("BILLINFO_ID")
	private java.lang.String billinfo_id;

 	public void setBillinfo_id(java.lang.String billinfo_id) {
		this.billinfo_id = billinfo_id;
	}

	public java.lang.String getBillinfo_id() {
		return billinfo_id;
	}

	@com.google.gson.annotations.SerializedName("UNAPPLIED_AMOUNT")
	private java.lang.String unapplied_amount;

 	/*public void setUnapplied_amount(java.lang.String unapplied_amount) {
		this.unapplied_amount = unapplied_amount;
	}*/

	public java.lang.Double getUnapplied_amount() {
		if(unapplied_amount == null || unapplied_amount.equalsIgnoreCase(""))
			return 0.0d;
		return Double.valueOf(unapplied_amount);
	}

	@com.google.gson.annotations.SerializedName("BILL_WHEN")
	private java.lang.String bill_when;

 	public void setBill_when(java.lang.String bill_when) {
		this.bill_when = bill_when;
	}

	public java.lang.String getBill_when() {
		return bill_when;
	}

	@com.google.gson.annotations.SerializedName("ACTUAL_LAST_BILL_OBJ")
	private java.lang.String actual_last_bill_obj;

 	public void setActual_last_bill_obj(java.lang.String actual_last_bill_obj) {
		this.actual_last_bill_obj = actual_last_bill_obj;
	}

	public java.lang.String getActual_last_bill_obj() {
		return actual_last_bill_obj;
	}
	
	@com.google.gson.annotations.SerializedName("BILLS")
	private BILLS bills;

 	public void setBills(BILLS bills) {
		this.bills = bills;
	}

	public BILLS getBills() {
		return bills;
	}
}