/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.BRM.CATV.GetCustomer;

public class DEVICEElement {
	@com.google.gson.annotations.SerializedName("MSO_FLD_EXT_WARRANTY_END")
	private java.lang.String mso_fld_ext_warranty_end;

 	public void setMso_fld_ext_warranty_end(java.lang.String mso_fld_ext_warranty_end) {
		this.mso_fld_ext_warranty_end = mso_fld_ext_warranty_end;
	}

	public java.lang.String getMso_fld_ext_warranty_end() {
		return mso_fld_ext_warranty_end;
	}

	@com.google.gson.annotations.SerializedName("SOURCE")
	private java.lang.String source;

 	public void setSource(java.lang.String source) {
		this.source = source;
	}

	public java.lang.String getSource() {
		return source;
	}

	@com.google.gson.annotations.SerializedName("DESCR")
	private java.lang.String descr;

 	public void setDescr(java.lang.String descr) {
		this.descr = descr;
	}

	public java.lang.String getDescr() {
		return descr;
	}

	@com.google.gson.annotations.SerializedName("POID")
	private java.lang.String poid;

 	public void setPoid(java.lang.String poid) {
		this.poid = poid;
	}

	public java.lang.String getPoid() {
		return poid;
	}

	@com.google.gson.annotations.SerializedName("DEVICE_ID")
	private java.lang.String device_id;

 	public void setDevice_id(java.lang.String device_id) {
		this.device_id = device_id;
	}

	public java.lang.String getDevice_id() {
		return device_id;
	}

	@com.google.gson.annotations.SerializedName("elem")
	private java.lang.String elem;

 	/*public void setElem(java.lang.Integer elem) {
		this.elem = elem;
	}*/

	public java.lang.Integer getElem() {
		if(elem == null || elem.equals(""))
			return 0;
		else
		return Integer.valueOf(elem);
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_SERIAL_NO")
	private java.lang.String mso_fld_serial_no;

 	public void setMso_fld_serial_no(java.lang.String mso_fld_serial_no) {
		this.mso_fld_serial_no = mso_fld_serial_no;
	}

	public java.lang.String getMso_fld_serial_no() {
		return mso_fld_serial_no;
	}

	@com.google.gson.annotations.SerializedName("MODEL")
	private java.lang.String model;

 	public void setModel(java.lang.String model) {
		this.model = model;
	}

	public java.lang.String getModel() {
		return model;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_WARRANTY_END")
	private java.lang.String mso_fld_warranty_end;

 	public void setMso_fld_warranty_end(java.lang.String mso_fld_warranty_end) {
		this.mso_fld_warranty_end = mso_fld_warranty_end;
	}

	public java.lang.String getMso_fld_warranty_end() {
		return mso_fld_warranty_end;
	}

	@com.google.gson.annotations.SerializedName("MANUFACTURER")
	private java.lang.String manufacturer;

 	public void setManufacturer(java.lang.String manufacturer) {
		this.manufacturer = manufacturer;
	}

	public java.lang.String getManufacturer() {
		return manufacturer;
	}

	@com.google.gson.annotations.SerializedName("DEVICE_TYPE")
	private java.lang.String device_type;

 	public void setDevice_type(java.lang.String device_type) {
		this.device_type = device_type;
	}

	public java.lang.String getDevice_type() {
		return device_type;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_WARRANTY_END_OFFSET")
	private java.lang.Integer mso_fld_warranty_end_offset;

 	public void setMso_fld_warranty_end_offset(java.lang.Integer mso_fld_warranty_end_offset) {
		this.mso_fld_warranty_end_offset = mso_fld_warranty_end_offset;
	}

	public java.lang.Integer getMso_fld_warranty_end_offset() {
		return mso_fld_warranty_end_offset;
	}

	@com.google.gson.annotations.SerializedName("STATE_ID")
	private java.lang.Integer state_id;

 	public void setState_id(java.lang.Integer state_id) {
		this.state_id = state_id;
	}

	public java.lang.Integer getState_id() {
		return state_id;
	}

}