/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.BRM.CATV.GetCustomer;

public class MEMBERElement {
	@com.google.gson.annotations.SerializedName("ACCOUNT_NO")
	private java.lang.String account_no;

 	public void setAccount_no(java.lang.String account_no) {
		this.account_no = account_no;
	}

	public java.lang.String getAccount_no() {
		return account_no;
	}

	@com.google.gson.annotations.SerializedName("NAMEINFO")
	private NAMEINFO nameinfo;

 	public void setNameinfo(NAMEINFO nameinfo) {
		this.nameinfo = nameinfo;
	}

	public NAMEINFO getNameinfo() {
		return nameinfo;
	}

	@com.google.gson.annotations.SerializedName("POID")
	private java.lang.String poid;

 	public void setPoid(java.lang.String poid) {
		this.poid = poid;
	}

	public java.lang.String getPoid() {
		return poid;
	}

	@com.google.gson.annotations.SerializedName("CONN_TYPE")
	private java.lang.Integer conn_type;

 	public void setConn_type(java.lang.Integer conn_type) {
		this.conn_type = conn_type;
	}

	public java.lang.Integer getConn_type() {
		return conn_type;
	}

	@com.google.gson.annotations.SerializedName("GROUP_OBJ")
	private java.lang.String group_obj;

 	public void setGroup_obj(java.lang.String group_obj) {
		this.group_obj = group_obj;
	}

	public java.lang.String getGroup_obj() {
		return group_obj;
	}

	@com.google.gson.annotations.SerializedName("elem")
	private java.lang.Integer elem;

 	public void setElem(java.lang.Integer elem) {
		this.elem = elem;
	}

	public java.lang.Integer getElem() {
		return elem;
	}

}