/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.BRM.CATV.GetCustomer;

public class MSO_FLD_CREDIT_PROFILE {
	@com.google.gson.annotations.SerializedName("elem")
	private java.lang.String elem;

 	/*public void setElem(java.lang.Integer elem) {
		this.elem = elem;
	}*/

	public java.lang.Integer getElem() {
		if(elem == null || elem.equals(""))
			return 0;
		else
		return Integer.valueOf(elem);
	}

	@com.google.gson.annotations.SerializedName("CREDIT_FLOOR")
	private java.lang.Integer credit_floor;

 	public void setCredit_floor(java.lang.Integer credit_floor) {
		this.credit_floor = credit_floor;
	}

	public java.lang.Integer getCredit_floor() {
		return credit_floor;
	}

	@com.google.gson.annotations.SerializedName("CREDIT_LIMIT")
	private java.lang.Integer credit_limit;

 	public void setCredit_limit(java.lang.Integer credit_limit) {
		this.credit_limit = credit_limit;
	}

	public java.lang.Integer getCredit_limit() {
		return credit_limit;
	}

	@com.google.gson.annotations.SerializedName("CURRENT_BAL")
	private java.lang.Double current_bal;

 	public void setCurrent_bal(java.lang.Double current_bal) {
		this.current_bal = current_bal;
	}

	public java.lang.Double getCurrent_bal() {
		return current_bal;
	}

}