/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.BRM.CATV.GetCustomer;

public class MSO_OP_CUST_GET_CUSTOMER_INFO_outputFlist {
	@com.google.gson.annotations.SerializedName("MSO_FLD_ORG_STRUCTURE")
	private MSO_FLD_ORG_STRUCTURE mso_fld_org_structure;

 	public void setMso_fld_org_structure(MSO_FLD_ORG_STRUCTURE mso_fld_org_structure) {
		this.mso_fld_org_structure = mso_fld_org_structure;
	}

	public MSO_FLD_ORG_STRUCTURE getMso_fld_org_structure() {
		return mso_fld_org_structure;
	}

	@com.google.gson.annotations.SerializedName("SERVICE_INFO")
	private SERVICE_INFO service_info;

 	public void setService_info(SERVICE_INFO service_info) {
		this.service_info = service_info;
	}

	public SERVICE_INFO getService_info() {
		return service_info;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_CONTACT_PREF")
	private java.lang.Integer mso_fld_contact_pref;

 	public void setMso_fld_contact_pref(java.lang.Integer mso_fld_contact_pref) {
		this.mso_fld_contact_pref = mso_fld_contact_pref;
	}

	public java.lang.Integer getMso_fld_contact_pref() {
		return mso_fld_contact_pref;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_CREDIT_PROFILE")
	private MSO_FLD_CREDIT_PROFILE[] mso_fld_credit_profile;

 	public MSO_FLD_CREDIT_PROFILE[] getMso_fld_credit_profile() {
		return mso_fld_credit_profile;
	}

	public void setMso_fld_credit_profile(MSO_FLD_CREDIT_PROFILE[] mso_fld_credit_profile) {
		this.mso_fld_credit_profile = mso_fld_credit_profile;
	}

	@com.google.gson.annotations.SerializedName("GROUP_INFO")
	private GROUP_INFO group_info;

 	public void setGroup_info(GROUP_INFO group_info) {
		this.group_info = group_info;
	}

	public GROUP_INFO getGroup_info() {
		return group_info;
	}

	@com.google.gson.annotations.SerializedName("ACCOUNT_NO")
	private java.lang.String account_no;

 	public void setAccount_no(java.lang.String account_no) {
		this.account_no = account_no;
	}

	public java.lang.String getAccount_no() {
		return account_no;
	}

	@com.google.gson.annotations.SerializedName("LOGIN")
	private java.lang.String login;

 	public void setLogin(java.lang.String login) {
		this.login = login;
	}

	public java.lang.String getLogin() {
		return login;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_DATA_ACCESS")
	private java.lang.String mso_fld_data_access;

 	public void setMso_fld_data_access(java.lang.String mso_fld_data_access) {
		this.mso_fld_data_access = mso_fld_data_access;
	}

	public java.lang.String getMso_fld_data_access() {
		return mso_fld_data_access;
	}

	@com.google.gson.annotations.SerializedName("CREATED_T")
	private java.lang.String created_t;

 	public void setCreated_t(java.lang.String created_t) {
		this.created_t = created_t;
	}

	public java.lang.String getCreated_t() {
		return created_t;
	}

	@com.google.gson.annotations.SerializedName("POID")
	private java.lang.String poid;

 	public void setPoid(java.lang.String poid) {
		this.poid = poid;
	}

	public java.lang.String getPoid() {
		return poid;
	}

	@com.google.gson.annotations.SerializedName("PROFILE_OBJ")
	private java.lang.String profile_obj;

 	public void setProfile_obj(java.lang.String profile_obj) {
		this.profile_obj = profile_obj;
	}

	public java.lang.String getProfile_obj() {
		return profile_obj;
	}

	@com.google.gson.annotations.SerializedName("LASTSTAT_CMNT")
	private java.lang.String laststat_cmnt;

 	public void setLaststat_cmnt(java.lang.String laststat_cmnt) {
		this.laststat_cmnt = laststat_cmnt;
	}

	public java.lang.String getLaststat_cmnt() {
		return laststat_cmnt;
	}

	@com.google.gson.annotations.SerializedName("MOD_T")
	private java.lang.String mod_t;

 	public void setMod_t(java.lang.String mod_t) {
		this.mod_t = mod_t;
	}

	public java.lang.String getMod_t() {
		return mod_t;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_LEGACY_ACCOUNT_NO")
	private java.lang.String mso_fld_legacy_account_no;

 	public void setMso_fld_legacy_account_no(java.lang.String mso_fld_legacy_account_no) {
		this.mso_fld_legacy_account_no = mso_fld_legacy_account_no;
	}

	public java.lang.String getMso_fld_legacy_account_no() {
		return mso_fld_legacy_account_no;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_RMN")
	private java.lang.String mso_fld_rmn;

 	public void setMso_fld_rmn(java.lang.String mso_fld_rmn) {
		this.mso_fld_rmn = mso_fld_rmn;
	}

	public java.lang.String getMso_fld_rmn() {
		return mso_fld_rmn;
	}

	@com.google.gson.annotations.SerializedName("PARENT_FLAGS")
	private java.lang.Integer parent_flags;

 	public void setParent_flags(java.lang.Integer parent_flags) {
		this.parent_flags = parent_flags;
	}

	public java.lang.Integer getParent_flags() {
		return parent_flags;
	}

	@com.google.gson.annotations.SerializedName("NAMEINFO")
	private NAMEINFOElement[] nameinfo;

 	public void setNameinfo(NAMEINFOElement[] nameinfo) {
		this.nameinfo = nameinfo;
	}

	public NAMEINFOElement[] getNameinfo() {
		return nameinfo;
	}

	@com.google.gson.annotations.SerializedName("PASSWD")
	private java.lang.String passwd;

 	public void setPasswd(java.lang.String passwd) {
		this.passwd = passwd;
	}

	public java.lang.String getPasswd() {
		return passwd;
	}

	@com.google.gson.annotations.SerializedName("BUSINESS_TYPE")
	private java.lang.Integer business_type;

 	public void setBusiness_type(java.lang.Integer business_type) {
		this.business_type = business_type;
	}

	public java.lang.Integer getBusiness_type() {
		return business_type;
	}

	@com.google.gson.annotations.SerializedName("STATUS")
	private java.lang.Integer status;

 	public void setStatus(java.lang.Integer status) {
		this.status = status;
	}

	public java.lang.Integer getStatus() {
		return status;
	}
	
	@com.google.gson.annotations.SerializedName("BILLINFO")
	private BILLINFO billinfo;

	public BILLINFO getBillinfo() {
		return billinfo;
	}

	public void setBillinfo(BILLINFO billinfo) {
		this.billinfo = billinfo;
	}
}