/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.BRM.CATV.GetCustomer;

public class NAMEINFOElement {
	@com.google.gson.annotations.SerializedName("SERVICE_OBJ")
	private java.lang.String service_obj;

 	public void setService_obj(java.lang.String service_obj) {
		this.service_obj = service_obj;
	}

	public java.lang.String getService_obj() {
		return service_obj;
	}

	@com.google.gson.annotations.SerializedName("MIDDLE_NAME")
	private java.lang.String middle_name;

 	public void setMiddle_name(java.lang.String middle_name) {
		this.middle_name = middle_name;
	}

	public java.lang.String getMiddle_name() {
		return middle_name;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_DISTRICT_NAME")
	private java.lang.String mso_fld_district_name;

 	public void setMso_fld_district_name(java.lang.String mso_fld_district_name) {
		this.mso_fld_district_name = mso_fld_district_name;
	}

	public java.lang.String getMso_fld_district_name() {
		return mso_fld_district_name;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_LANDMARK")
	private java.lang.String mso_fld_landmark;

 	public void setMso_fld_landmark(java.lang.String mso_fld_landmark) {
		this.mso_fld_landmark = mso_fld_landmark;
	}

	public java.lang.String getMso_fld_landmark() {
		return mso_fld_landmark;
	}

	@com.google.gson.annotations.SerializedName("ZIP")
	private java.lang.Integer zip;

 	public void setZip(java.lang.Integer zip) {
		this.zip = zip;
	}

	public java.lang.Integer getZip() {
		return zip;
	}

	@com.google.gson.annotations.SerializedName("SALUTATION")
	private java.lang.String salutation;

 	public void setSalutation(java.lang.String salutation) {
		this.salutation = salutation;
	}

	public java.lang.String getSalutation() {
		return salutation;
	}

	@com.google.gson.annotations.SerializedName("CONTACT_TYPE")
	private java.lang.String contact_type;

 	public void setContact_type(java.lang.String contact_type) {
		this.contact_type = contact_type;
	}

	public java.lang.String getContact_type() {
		return contact_type;
	}

	@com.google.gson.annotations.SerializedName("COUNTRY")
	private java.lang.String country;

 	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public java.lang.String getCountry() {
		return country;
	}

	@com.google.gson.annotations.SerializedName("STATE")
	private java.lang.String state;

 	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getState() {
		return state;
	}

	@com.google.gson.annotations.SerializedName("GEOCODE")
	private java.lang.String geocode;

 	public void setGeocode(java.lang.String geocode) {
		this.geocode = geocode;
	}

	public java.lang.String getGeocode() {
		return geocode;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_LOCATION_NAME")
	private java.lang.String mso_fld_location_name;

 	public void setMso_fld_location_name(java.lang.String mso_fld_location_name) {
		this.mso_fld_location_name = mso_fld_location_name;
	}

	public java.lang.String getMso_fld_location_name() {
		return mso_fld_location_name;
	}

	@com.google.gson.annotations.SerializedName("FIRST_NAME")
	private java.lang.String first_name;

 	public void setFirst_name(java.lang.String first_name) {
		this.first_name = first_name;
	}

	public java.lang.String getFirst_name() {
		return first_name;
	}

	@com.google.gson.annotations.SerializedName("CANON_COUNTRY")
	private java.lang.String canon_country;

 	public void setCanon_country(java.lang.String canon_country) {
		this.canon_country = canon_country;
	}

	public java.lang.String getCanon_country() {
		return canon_country;
	}

	@com.google.gson.annotations.SerializedName("LAST_NAME")
	private java.lang.String last_name;

 	public void setLast_name(java.lang.String last_name) {
		this.last_name = last_name;
	}

	public java.lang.String getLast_name() {
		return last_name;
	}

	@com.google.gson.annotations.SerializedName("MIDDLE_CANON")
	private java.lang.String middle_canon;

 	public void setMiddle_canon(java.lang.String middle_canon) {
		this.middle_canon = middle_canon;
	}

	public java.lang.String getMiddle_canon() {
		return middle_canon;
	}

	@com.google.gson.annotations.SerializedName("LAST_CANON")
	private java.lang.String last_canon;

 	public void setLast_canon(java.lang.String last_canon) {
		this.last_canon = last_canon;
	}

	public java.lang.String getLast_canon() {
		return last_canon;
	}

	@com.google.gson.annotations.SerializedName("TITLE")
	private java.lang.String title;

 	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getTitle() {
		return title;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_STREET_NAME")
	private java.lang.String mso_fld_street_name;

 	public void setMso_fld_street_name(java.lang.String mso_fld_street_name) {
		this.mso_fld_street_name = mso_fld_street_name;
	}

	public java.lang.String getMso_fld_street_name() {
		return mso_fld_street_name;
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_BUILDING_NAME")
	private java.lang.String mso_fld_building_name;

 	public void setMso_fld_building_name(java.lang.String mso_fld_building_name) {
		this.mso_fld_building_name = mso_fld_building_name;
	}

	public java.lang.String getMso_fld_building_name() {
		return mso_fld_building_name;
	}

	@com.google.gson.annotations.SerializedName("FIRST_CANON")
	private java.lang.String first_canon;

 	public void setFirst_canon(java.lang.String first_canon) {
		this.first_canon = first_canon;
	}

	public java.lang.String getFirst_canon() {
		return first_canon;
	}

	@com.google.gson.annotations.SerializedName("TAXPKG_TYPE")
	private java.lang.Integer taxpkg_type;

 	public void setTaxpkg_type(java.lang.Integer taxpkg_type) {
		this.taxpkg_type = taxpkg_type;
	}

	public java.lang.Integer getTaxpkg_type() {
		return taxpkg_type;
	}

	@com.google.gson.annotations.SerializedName("ADDRESS")
	private java.lang.String address;

 	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getAddress() {
		return address;
	}

	@com.google.gson.annotations.SerializedName("CANON_COMPANY")
	private java.lang.String canon_company;

 	public void setCanon_company(java.lang.String canon_company) {
		this.canon_company = canon_company;
	}

	public java.lang.String getCanon_company() {
		return canon_company;
	}

	@com.google.gson.annotations.SerializedName("elem")
	private java.lang.String elem;

 	/*public void setElem(java.lang.Integer elem) {
		this.elem = elem;
	}*/

	public java.lang.Integer getElem() {
		if(elem == null || elem.equals(""))
			return 0;
		else
		return Integer.valueOf(elem);
	}

	@com.google.gson.annotations.SerializedName("MSO_FLD_AREA_NAME")
	private java.lang.String mso_fld_area_name;

 	public void setMso_fld_area_name(java.lang.String mso_fld_area_name) {
		this.mso_fld_area_name = mso_fld_area_name;
	}

	public java.lang.String getMso_fld_area_name() {
		return mso_fld_area_name;
	}

	@com.google.gson.annotations.SerializedName("CITY")
	private java.lang.String city;

 	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getCity() {
		return city;
	}

	@com.google.gson.annotations.SerializedName("EMAIL_ADDR")
	private java.lang.String email_addr;

 	public void setEmail_addr(java.lang.String email_addr) {
		this.email_addr = email_addr;
	}

	public java.lang.String getEmail_addr() {
		return email_addr;
	}

	@com.google.gson.annotations.SerializedName("COMPANY")
	private java.lang.String company;

 	public void setCompany(java.lang.String company) {
		this.company = company;
	}

	public java.lang.String getCompany() {
		return company;
	}

	@com.google.gson.annotations.SerializedName("PHONES")
	private PHONElement[] phones;

 	public void setPhones(PHONElement[] phones) {
		this.phones = phones;
	}

	public PHONElement[] getPhones() {
		return phones;
	}

}