/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.BRM.CATV.GetCustomer;

public class PLAN_LISTElement {
	@com.google.gson.annotations.SerializedName("PLAN")
	private PLANElement[] plan;

 	public void setPlan(PLANElement[] plan) {
		this.plan = plan;
	}

	public PLANElement[] getPlan() {
		return plan;
	}

	@com.google.gson.annotations.SerializedName("elem")
	private java.lang.String elem;

 	/*public void setElem(java.lang.Integer elem) {
		this.elem = elem;
	}*/

	public java.lang.Integer getElem() {
		if(elem == null || elem.equals(""))
			return 0;
		else
		return Integer.valueOf(elem);
	}

}