/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.BRM.CATV.GetCustomer;

public class SERVICEElement {
	@com.google.gson.annotations.SerializedName("MSO_FLD_CATV_INFO")
	private MSO_FLD_CATV_INFO mso_fld_catv_info;

 	public void setMso_fld_catv_info(MSO_FLD_CATV_INFO mso_fld_catv_info) {
		this.mso_fld_catv_info = mso_fld_catv_info;
	}

	public MSO_FLD_CATV_INFO getMso_fld_catv_info() {
		return mso_fld_catv_info;
	}

	@com.google.gson.annotations.SerializedName("LOGIN")
	private java.lang.String login;

 	public void setLogin(java.lang.String login) {
		this.login = login;
	}

	public java.lang.String getLogin() {
		return login;
	}

	@com.google.gson.annotations.SerializedName("SERVICE_ID")
	private java.lang.String service_id;

 	public void setService_id(java.lang.String service_id) {
		this.service_id = service_id;
	}

	public java.lang.String getService_id() {
		return service_id;
	}

	@com.google.gson.annotations.SerializedName("AAC_ACCESS")
	private java.lang.String aac_access;

 	public void setAac_access(java.lang.String aac_access) {
		this.aac_access = aac_access;
	}

	public java.lang.String getAac_access() {
		return aac_access;
	}

	@com.google.gson.annotations.SerializedName("CREATED_T")
	private java.lang.String created_t;

 	public void setCreated_t(java.lang.String created_t) {
		this.created_t = created_t;
	}

	public java.lang.String getCreated_t() {
		return created_t;
	}

	@com.google.gson.annotations.SerializedName("PROFILE_OBJ")
	private java.lang.String profile_obj;

 	public void setProfile_obj(java.lang.String profile_obj) {
		this.profile_obj = profile_obj;
	}

	public java.lang.String getProfile_obj() {
		return profile_obj;
	}

	@com.google.gson.annotations.SerializedName("BAL_GRP_OBJ")
	private java.lang.String bal_grp_obj;

 	public void setBal_grp_obj(java.lang.String bal_grp_obj) {
		this.bal_grp_obj = bal_grp_obj;
	}

	public java.lang.String getBal_grp_obj() {
		return bal_grp_obj;
	}

	@com.google.gson.annotations.SerializedName("LASTSTAT_CMNT")
	private java.lang.String laststat_cmnt;

 	public void setLaststat_cmnt(java.lang.String laststat_cmnt) {
		this.laststat_cmnt = laststat_cmnt;
	}

	public java.lang.String getLaststat_cmnt() {
		return laststat_cmnt;
	}

	@com.google.gson.annotations.SerializedName("SERVICE_STATE_EXPIRATION_T")
	private java.lang.String service_state_expiration_t;

 	public void setService_state_expiration_t(java.lang.String service_state_expiration_t) {
		this.service_state_expiration_t = service_state_expiration_t;
	}

	public java.lang.String getService_state_expiration_t() {
		return service_state_expiration_t;
	}

	@com.google.gson.annotations.SerializedName("MOD_T")
	private java.lang.String mod_t;

 	public void setMod_t(java.lang.String mod_t) {
		this.mod_t = mod_t;
	}

	public java.lang.String getMod_t() {
		return mod_t;
	}

	@com.google.gson.annotations.SerializedName("TYPE")
	private java.lang.Integer type;

 	public void setType(java.lang.Integer type) {
		this.type = type;
	}

	public java.lang.Integer getType() {
		return type;
	}

	@com.google.gson.annotations.SerializedName("READ_ACCESS")
	private java.lang.String read_access;

 	public void setRead_access(java.lang.String read_access) {
		this.read_access = read_access;
	}

	public java.lang.String getRead_access() {
		return read_access;
	}

	@com.google.gson.annotations.SerializedName("LIFECYCLE_STATE")
	private java.lang.Integer lifecycle_state;

 	public void setLifecycle_state(java.lang.Integer lifecycle_state) {
		this.lifecycle_state = lifecycle_state;
	}

	public java.lang.Integer getLifecycle_state() {
		return lifecycle_state;
	}

	@com.google.gson.annotations.SerializedName("PASSWD_EXPIRATION_T")
	private java.lang.String passwd_expiration_t;

 	public void setPasswd_expiration_t(java.lang.String passwd_expiration_t) {
		this.passwd_expiration_t = passwd_expiration_t;
	}

	public java.lang.String getPasswd_expiration_t() {
		return passwd_expiration_t;
	}

	@com.google.gson.annotations.SerializedName("STATUS_FLAGS")
	private java.lang.Integer status_flags;

 	public void setStatus_flags(java.lang.Integer status_flags) {
		this.status_flags = status_flags;
	}

	public java.lang.Integer getStatus_flags() {
		return status_flags;
	}

	@com.google.gson.annotations.SerializedName("NEXT_ITEM_POID_LIST")
	private java.lang.String next_item_poid_list;

 	public void setNext_item_poid_list(java.lang.String next_item_poid_list) {
		this.next_item_poid_list = next_item_poid_list;
	}

	public java.lang.String getNext_item_poid_list() {
		return next_item_poid_list;
	}

	@com.google.gson.annotations.SerializedName("PASSWD_STATUS")
	private java.lang.Integer passwd_status;

 	public void setPasswd_status(java.lang.Integer passwd_status) {
		this.passwd_status = passwd_status;
	}

	public java.lang.Integer getPasswd_status() {
		return passwd_status;
	}

	@com.google.gson.annotations.SerializedName("PLAN_LISTS")
	private PLAN_LISTElement[] plan_lists;

 	public void setPlan_lists(PLAN_LISTElement[] plan_lists) {
		this.plan_lists = plan_lists;
	}

	public PLAN_LISTElement[] getPlan_lists() {
		return plan_lists;
	}

	@com.google.gson.annotations.SerializedName("WRITE_ACCESS")
	private java.lang.String write_access;

 	public void setWrite_access(java.lang.String write_access) {
		this.write_access = write_access;
	}

	public java.lang.String getWrite_access() {
		return write_access;
	}

	@com.google.gson.annotations.SerializedName("SUBSCRIPTION_OBJ")
	private java.lang.String subscription_obj;

 	public void setSubscription_obj(java.lang.String subscription_obj) {
		this.subscription_obj = subscription_obj;
	}

	public java.lang.String getSubscription_obj() {
		return subscription_obj;
	}

	@com.google.gson.annotations.SerializedName("STATUS")
	private java.lang.String status;

 	/*public void setStatus(java.lang.Integer status) {
		this.status = status;
	}*/

	public java.lang.Integer getStatus() {
		if(status == null || status.equals(""))
			return 0;
		else
		return Integer.valueOf(status);
	}

	@com.google.gson.annotations.SerializedName("EFFECTIVE_T")
	private java.lang.String effective_t;

 	public void setEffective_t(java.lang.String effective_t) {
		this.effective_t = effective_t;
	}

	public java.lang.String getEffective_t() {
		return effective_t;
	}

	@com.google.gson.annotations.SerializedName("POID")
	private java.lang.String poid;

 	public void setPoid(java.lang.String poid) {
		this.poid = poid;
	}

	public java.lang.String getPoid() {
		return poid;
	}

	@com.google.gson.annotations.SerializedName("CLOSE_WHEN_T")
	private java.lang.String close_when_t;

 	public void setClose_when_t(java.lang.String close_when_t) {
		this.close_when_t = close_when_t;
	}

	public java.lang.String getClose_when_t() {
		return close_when_t;
	}

	@com.google.gson.annotations.SerializedName("AAC_VENDOR")
	private java.lang.String aac_vendor;

 	public void setAac_vendor(java.lang.String aac_vendor) {
		this.aac_vendor = aac_vendor;
	}

	public java.lang.String getAac_vendor() {
		return aac_vendor;
	}

	@com.google.gson.annotations.SerializedName("AAC_SOURCE")
	private java.lang.String aac_source;

 	public void setAac_source(java.lang.String aac_source) {
		this.aac_source = aac_source;
	}

	public java.lang.String getAac_source() {
		return aac_source;
	}

	@com.google.gson.annotations.SerializedName("OBJECT_CACHE_TYPE")
	private java.lang.Integer object_cache_type;

 	public void setObject_cache_type(java.lang.Integer object_cache_type) {
		this.object_cache_type = object_cache_type;
	}

	public java.lang.Integer getObject_cache_type() {
		return object_cache_type;
	}

	@com.google.gson.annotations.SerializedName("AAC_SERIAL_NUM")
	private java.lang.String aac_serial_num;

 	public void setAac_serial_num(java.lang.String aac_serial_num) {
		this.aac_serial_num = aac_serial_num;
	}

	public java.lang.String getAac_serial_num() {
		return aac_serial_num;
	}

	@com.google.gson.annotations.SerializedName("elem")
	private java.lang.String elem;

 	/*public void setElem(java.lang.Integer elem) {
		this.elem = elem;
	}*/

	public java.lang.Integer getElem() {
		if(elem == null || elem.equals(""))
			return 0;
		else
		return Integer.valueOf(elem);
	}

	@com.google.gson.annotations.SerializedName("ALIAS_LIST")
	private ALIAS_LISTElement[] alias_list;

 	public void setAlias_list(ALIAS_LISTElement[] alias_list) {
		this.alias_list = alias_list;
	}

	public ALIAS_LISTElement[] getAlias_list() {
		return alias_list;
	}

	@com.google.gson.annotations.SerializedName("LAST_STATUS_T")
	private java.lang.String last_status_t;

 	public void setLast_status_t(java.lang.String last_status_t) {
		this.last_status_t = last_status_t;
	}

	public java.lang.String getLast_status_t() {
		return last_status_t;
	}

	@com.google.gson.annotations.SerializedName("AAC_PACKAGE")
	private java.lang.String aac_package;

 	public void setAac_package(java.lang.String aac_package) {
		this.aac_package = aac_package;
	}

	public java.lang.String getAac_package() {
		return aac_package;
	}

	@com.google.gson.annotations.SerializedName("AAC_PROMO_CODE")
	private java.lang.String aac_promo_code;

 	public void setAac_promo_code(java.lang.String aac_promo_code) {
		this.aac_promo_code = aac_promo_code;
	}

	public java.lang.String getAac_promo_code() {
		return aac_promo_code;
	}

	@com.google.gson.annotations.SerializedName("NAME")
	private java.lang.String name;

 	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

	@com.google.gson.annotations.SerializedName("ACCOUNT_OBJ")
	private java.lang.String account_obj;

 	public void setAccount_obj(java.lang.String account_obj) {
		this.account_obj = account_obj;
	}

	public java.lang.String getAccount_obj() {
		return account_obj;
	}

	@com.google.gson.annotations.SerializedName("DEVICES")
	private DEVICEElement[] devices;

 	public void setDevices(DEVICEElement[] devices) {
		this.devices = devices;
	}

	public DEVICEElement[] getDevices() {
		return devices;
	}

	@com.google.gson.annotations.SerializedName("ITEM_POID_LIST")
	private java.lang.String item_poid_list;

 	public void setItem_poid_list(java.lang.String item_poid_list) {
		this.item_poid_list = item_poid_list;
	}

	public java.lang.String getItem_poid_list() {
		return item_poid_list;
	}

	@com.google.gson.annotations.SerializedName("PASSWD")
	private java.lang.String passwd;

 	public void setPasswd(java.lang.String passwd) {
		this.passwd = passwd;
	}

	public java.lang.String getPasswd() {
		return passwd;
	}

}