/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.BRM.CATV.GetReceipts;

public class CATVReceiptsMaster {
	@com.google.gson.annotations.SerializedName("MSO_OP_PYMT_GET_RECEIPTS_outputFlist")
	private MSO_OP_PYMT_GET_RECEIPTS_outputFlist mso_op_pymt_get_receipts_outputflist;

 	public void setMso_op_pymt_get_receipts_outputflist(MSO_OP_PYMT_GET_RECEIPTS_outputFlist mso_op_pymt_get_receipts_outputflist) {
		this.mso_op_pymt_get_receipts_outputflist = mso_op_pymt_get_receipts_outputflist;
	}

	public MSO_OP_PYMT_GET_RECEIPTS_outputFlist getMso_op_pymt_get_receipts_outputflist() {
		return mso_op_pymt_get_receipts_outputflist;
	}

}