/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.BRM.CATV.GetReceipts;

public class MSO_OP_PYMT_GET_RECEIPTS_outputFlist {
	@com.google.gson.annotations.SerializedName("POID")
	private java.lang.String poid;

 	public void setPoid(java.lang.String poid) {
		this.poid = poid;
	}

	public java.lang.String getPoid() {
		return poid;
	}

	@com.google.gson.annotations.SerializedName("STATUS")
	private java.lang.String status;

 	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getStatus() {
		return status;
	}

	@com.google.gson.annotations.SerializedName("RESULTS")
	private RESULTElement[] results;

 	public void setResults(RESULTElement[] results) {
		this.results = results;
	}

	public RESULTElement[] getResults() {
		return results;
	}

}